apiVersion: v1
kind: Pod
metadata:
  name: test-downwardapi-volume
  labels:
    app: test-downwardapi-volume
    zone: us-est-coast
    cluster: test-cluster-1
    rack: rack-22
spec:
  containers:
    - name: client-container
      image: k8s.gcr.io/busybox
      command:
        - "sh"
        - "-c"
      args:
        - while true; do
            if [[ -e /etc/podinfo/labels ]]; then
              echo -en '\n\n'; cat /etc/podinfo/labels;
            fi;
            sleep 5;
          done;
      volumeMounts:
        - mountPath: /etc/podinfo
          name: podinfo
          readOnly: true
  volumes:
    - name: podinfo
      projected:  # 声明 projected 类型的 Volume
        sources:
          - downwardAPI:  # 数据来源是 downwardAPI
              items:
                - path: "labels"
                  fieldRef:
                    fieldPath: metadata.labels  # 声明暴露 Pod 的 metadata.labels 信息给容器
  