apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-role
  namespace: mynamespace  # 产生作用的 Namespace，Kubernetes 的逻辑管理单位，默认 default
  labels:
    app: example-role
rules:  # 权限规则
  - apiGroups: [""]
    resources: ["pods"] # 作用对象
    verbs: ["get", "watch", "list"] # 相关操作