# httpd.v1.yml
apiVersion: apps/v1 # 版本
kind: Deployment  # 资源类型
metadata: # 资源的元数据，name是必填项
  name: httpd
spec: # Deployment的规则说明
  selector:
    matchLabels:
      app: httpd
  revisionHistoryLimit: 10  # revision数量
  replicas: 3 # 副本数
  template: # Pod 模板
    metadata: # Pod 元数据
      labels:
        app: httpd
        run: httpd
    spec: # Pod 规格，定义 Pod 中每个容器的属性，name 和 image 必填
      containers:
      - name: httpd
        image: httpd:2.4.17
        ports:
        - containerPort: 80