apiVersion: apps/v1 # 版本
kind: Deployment  # 资源类型
metadata: # 资源的元数据，name是必填项
  name: my-nginx
spec: # Deployment的规则说明
  selector:
    matchLabels:
      app: my-nginx
  replicas: 5 # 副本数
  template: # Pod 模板
    metadata: # Pod 元数据
      labels:
        app: my-nginx
    spec: # Pod 规格，定义 Pod 中每个容器的属性，name 和 image 必填
      containers:
      - name: my-nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80