apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostnames
  labels:
    app: hostnames
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hostnames
  template:
    metadata:
      name: hostnames
      labels:
        app: hostnames
    spec:
      containers:
        - name: hostnames
          image: nginx
          ports:
            - containerPort: 9376 # 容器访问端口
              protocol: TCP