apiVersion: v1
kind: Pod
metadata:
  name: test-projected-volume
  labels:
    app: test-projected-volume
spec:
  containers:
    - name: test-projected-volume
      image: busybox
      args:
        - sleep
        - "86400"
      volumeMounts:
        - mountPath: "/projected-volume"
          name: mysql-cred
          readOnly: true
  volumes:
    - name: mysql-cred
      projected:  # 声明挂载的 Volume 是 projected 类型
        sources:  # Volume 的数据来源，是 user 和 pass 的 Secret 对象
          - secret:
              name: user
          - secret:
              name: pass