# mypod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: mypod
spec:
  containers:
    - name: mypod
      image: busybox
      args:
        - /bin/sh
        - -c
        - sleep 10; touch /tmp/healthy; sleep 30000
      # 将 foo mount 到容器路径 /etc/foo，可指定读写权限为 readOnly
      volumeMounts:
        - mountPath: "/etc/foo"
          name: foo
          readOnly: true
  # 定义 volume foo，来源为 secret mysecret
  volumes:
    - name: foo
      secret:
        secretName: mysecret
        items:
          - key: username
            # 自定义存放数据的文件名
            path: my-group/my-username
          - key: password
            path: my-group/my-password