# mypod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: mypod
spec:
  containers:
    - name: mypod
      image: busybox
      args:
        - /bin/sh
        - -c
        - sleep 10; touch /tmp/healthy; sleep 30000
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: mysecret
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysecret