apiVersion: v1
kind: Service
metadata:
  name: my-nginx
spec:
  type: NodePort
  selector:
    app: my-nginx
    run: my-nginx
  ports:
    - nodePort: 8080  # Service 的 8080 端口代理 Pod 的 80 端口
      targetPort: 80
      protocol: TCP
      name: http
      port: 80
    - nodePort: 443 # Service 的 433 端口代理 Pod 的 433 端口
      targetPort: 433
      port: 433
      name: https
  